# Configuración de la aplicación Gestión de Tareas
server.port=8080

# Deshabilitar caché de Thymeleaf en desarrollo
spring.thymeleaf.cache=false

# Nombre de la aplicación
spring.application.name=tareas
